import Foundation

struct DecorationFactory {

  static func allDecorations() -> [Transformation] {
    return [
      Transformation(name: "Decoration ", before: "`•.,¸¸,.•´¯", after: "¯`•.,¸¸,.•´"),
      Transformation(name: "Decoration ", before: "¸,ø¤º°`°º¤ø,¸", after: "¸,ø¤º°`°º¤ø,¸"),
      Transformation(name: "Decoration ", before: "★·.·´¯`·.·★", after: "★·.·´¯`·.·★"),
      Transformation(name: "Decoration ", before: "¸„.-•~¹°”ˆ˜¨", after: "¨˜ˆ”°¹~•-.„¸"),
      Transformation(name: "Decoration ", before: "·.¸¸.·♩♪♫", after: "♫♪♩·.¸¸.·"),
      Transformation(name: "Decoration ", before: "×º°”˜`”°º×", after: "×º°”˜`”°º×"),
      Transformation(name: "Decoration ", before: "•?((¯°·._.•", after: "•._.·°¯))؟•"),
      Transformation(name: "Decoration ", before: "(¯´•._.•", after: "•._.•´¯)"),
      Transformation(name: "Decoration ", before: "¸„.-•~¹°”ˆ˜¨", after: "¨˜ˆ”°¹~•-.„¸"),
      Transformation(name: "Decoration ", before: "|!¤*'~``~'*¤!|", after: "|!¤*'~``~'*¤!|"),
      Transformation(name: "Decoration ", before: "(¯`·.¸¸.·´¯`·.¸¸.->", after: "<-.¸¸.·´¯`·.¸¸.·´¯)"),
      Transformation(name: "Decoration ", before: ",-*' ^ '~*-.,_,.-*~", after: "~*-.,_,.-*~' ^ '*-,"),
      Transformation(name: "Decoration ", before: "°°°·.°·..·°¯°·._.·", after: "·._.·°¯°·.·° .·°°°"),
      Transformation(name: "Decoration ", before: "•._.••´¯``•.¸¸.•`", after: "`•.¸¸.•´´¯`••._.•"),
      Transformation(name: "Decoration ", before: "¸,ø¤º°`°º¤ø,¸¸,ø¤º°", after: "°º¤ø,¸¸,ø¤º°`°º¤ø,¸"),
      Transformation(name: "Decoration ", before: ".•°¤*(¯`★´¯)*¤°", after: "°¤*(¯´★`¯)*¤°•."),
      Transformation(name: "Decoration ", before: "¤¸¸.•´¯`•¸¸.•..>>", after: "<<..•.¸¸•´¯`•.¸¸¤"),
      Transformation(name: "Decoration ", before: "`•.¸¸.•´´¯`••._.•", after: "•._.••`¯´´•.¸¸.•`"),
      Transformation(name: "Decoration ", before: "(¯´•._.•", after: "•._.•´¯)"),
      Transformation(name: "Decoration ", before: "••¤(`×[¤", after: "¤]×´)¤••"),
      Transformation(name: "Decoration ", before: "•´¯`•»", after: "«•´¯`•"),
      Transformation(name: "Decoration ", before: "—(••÷[", after: "]÷••)—"),
      Transformation(name: "Decoration ", before: "•]••´º´•»", after: "«•´º´••[•"),
      Transformation(name: "Decoration ", before: "*•.¸♡", after: "♡¸.•*"),
      Transformation(name: "Decoration ", before: "╰☆☆", after: "☆☆╮"),
      Transformation(name: "Decoration ", before: "↤↤↤↤↤↤", after: "↦↦↦↦↦↦"),
      Transformation(name: "Decoration ", before: "➶➶➶➶➶➶", after: "➷➷➷➷➷➷"),
      Transformation(name: "Decoration ", before: "↫↫↫↫↫", after: "↬↬↬↬↬"),
      Transformation(name: "Decoration ", before: "╚»★«╝", after: "╚»★«╝"),
      Transformation(name: "Decoration ", before: "•´¯`•.", after: ".•´¯`•"),
      Transformation(name: "Decoration ", before: "§.•´¨'°÷•..×", after: "×,.•´¨'°÷•..§"),
      Transformation(name: "Decoration ", before: "•°¯`••", after: "••´¯°•"),
      Transformation(name: "Decoration ", before: "]|I{•------»", after: "«------•}I|["),
      Transformation(name: "Decoration ", before: "(-_-)", after: "(-_-)"),
      Transformation(name: "Decoration ", before: "•´¯`•.", after: ".•´¯`•"),
      Transformation(name: "Decoration ", before: "-漫~*'¨¯¨'*·舞~", after: "~舞*'¨¯¨'*·~漫-"),
      Transformation(name: "Decoration ", before: "¤¸¸.•´¯`•¸¸.•..>>", after: "<<..•.¸¸•´¯`•.¸¸¤"),
      Transformation(name: "Decoration ", before: "๑۞๑,¸¸,ø¤º°`°๑۩", after: "๑۩ ,¸¸,ø¤º°`°๑۞๑"),
      Transformation(name: "Decoration ", before: ".•°¤*(¯`★´¯)*¤°", after: "°¤*(¯´★`¯)*¤°•."),
      Transformation(name: "Decoration ", before: "••.•´¯`•.••", after: "••.•´¯`•.••"),
      Transformation(name: "Decoration ", before: ".o0×X×0o.", after: ".o0×X×0o."),
      Transformation(name: "Decoration ", before: "ıllıllı", after: "ıllıllı"),
      Transformation(name: "Decoration ", before: "▀▄▀▄▀▄", after: "▄▀▄▀▄▀"),
      Transformation(name: "Decoration ", before: "▁ ▂ ▄ ▅ ▆ ▇ █", after: "█ ▇ ▆ ▅ ▄ ▂ ▁"),
      Transformation(name: "Decoration ", before: "▌│█║▌║▌║", after: "║▌║▌║█│▌"),
      Transformation(name: "Decoration ", before: "░▒▓█", after: "█▓▒░"),
      Transformation(name: "Decoration ", before: "░▒▓█►─═", after: "═─◄█▓▒░"),
      Transformation(name: "Decoration ", before: "ஜ۩۞۩ஜ", after: "ஜ۩۞۩ஜ"),
      Transformation(name: "Decoration ", before: "★彡", after: "彡★"),
      Transformation(name: "Decoration ", before: "◦•●◉✿", after: "✿◉●•◦"),
      Transformation(name: "Decoration ", before: "۰۪۫ ۪۫☃۰۪۫ ۪۫ ", after: "۰۪۫ ۪۫☃۰۪۫ ۪۫ "),
      Transformation(name: "Decoration ", before: "✦ (　-_･) ︻デ═一 ▸", after: "(/❛o❛)/ ✦"),
      Transformation(name: "Decoration ", before: "♔ (◐ ε ◑)", after: "(◐ ε ◑) ♔"),
      Transformation(name: "Decoration ", before: "★ 乂❤‿❤乂", after: "乂❤‿❤乂 ★"),
      Transformation(name: "Decoration ", before: "¯\\_(ツ)_/¯", after: "¯\\_(ツ)_/¯"),
      Transformation(name: "Decoration ", before: "♬♪♫", after: "ヾ(*・。・)ﾉ ♬♪♫"),
      Transformation(name: "Decoration ", before: "꧁꧂ ヽ(⌐■_■)ノ♪♬", after: "♬♪♫ ꧁꧂"),
      Transformation(name: "Decoration ", before: "ƪ(˘⌣˘)┐", after: "┌(˘⌣˘)ʃ"),
      Transformation(name: "Decoration ", before: "( ˘ ³˘)❤", after: "( ˘ ³˘)❤"),
      Transformation(name: "Decoration ", before: "༼ つ ◕_◕ ༽つ", after: "༼ つ ◕_◕ ༽つ"),
      Transformation(name: "Decoration ", before: "ヘ( ^o^)ノ", after: "＼(^_^ )"),
      Transformation(name: "Decoration ", before: "(~˘▾˘)~", after: "~(˘▾˘~)"),
      Transformation(name: "Decoration ", before: "└(^o^ )", after: "( ^o^)┘")
    ]
  }

}
