import Foundation

struct DecorationFactory {

  static func allDecorations() -> [Transformer] {
    return [
      Transformer(name: "Decoration ", before: "`•.,¸¸,.•´¯", after: "¯`•.,¸¸,.•´"),
      Transformer(name: "Decoration ", before: "¸,ø¤º°`°º¤ø,¸", after: "¸,ø¤º°`°º¤ø,¸"),
      Transformer(name: "Decoration ", before: "★·.·´¯`·.·★", after: "★·.·´¯`·.·★"),
      Transformer(name: "Decoration ", before: "¸„.-•~¹°”ˆ˜¨", after: "¨˜ˆ”°¹~•-.„¸"),
      Transformer(name: "Decoration ", before: "·.¸¸.·♩♪♫", after: "♫♪♩·.¸¸.·"),
      Transformer(name: "Decoration ", before: "×º°”˜`”°º×", after: "×º°”˜`”°º×"),
      Transformer(name: "Decoration ", before: "•?((¯°·._.•", after: "•._.·°¯))؟•"),
      Transformer(name: "Decoration ", before: "(¯´•._.•", after: "•._.•´¯)"),
      Transformer(name: "Decoration ", before: "¸„.-•~¹°”ˆ˜¨", after: "¨˜ˆ”°¹~•-.„¸"),
      Transformer(name: "Decoration ", before: "|!¤*'~``~'*¤!|", after: "|!¤*'~``~'*¤!|"),
      Transformer(name: "Decoration ", before: "(¯`·.¸¸.·´¯`·.¸¸.->", after: "<-.¸¸.·´¯`·.¸¸.·´¯)"),
      Transformer(name: "Decoration ", before: ",-*' ^ '~*-.,_,.-*~", after: "~*-.,_,.-*~' ^ '*-,"),
      Transformer(name: "Decoration ", before: "°°°·.°·..·°¯°·._.·", after: "·._.·°¯°·.·° .·°°°"),
      Transformer(name: "Decoration ", before: "•._.••´¯``•.¸¸.•`", after: "`•.¸¸.•´´¯`••._.•"),
      Transformer(name: "Decoration ", before: "¸,ø¤º°`°º¤ø,¸¸,ø¤º°", after: "°º¤ø,¸¸,ø¤º°`°º¤ø,¸"),
      Transformer(name: "Decoration ", before: ".•°¤*(¯`★´¯)*¤°", after: "°¤*(¯´★`¯)*¤°•."),
      Transformer(name: "Decoration ", before: "¤¸¸.•´¯`•¸¸.•..>>", after: "<<..•.¸¸•´¯`•.¸¸¤"),
      Transformer(name: "Decoration ", before: "`•.¸¸.•´´¯`••._.•", after: "•._.••`¯´´•.¸¸.•`"),
      Transformer(name: "Decoration ", before: "(¯´•._.•", after: "•._.•´¯)"),
      Transformer(name: "Decoration ", before: "••¤(`×[¤", after: "¤]×´)¤••"),
      Transformer(name: "Decoration ", before: "•´¯`•»", after: "«•´¯`•"),
      Transformer(name: "Decoration ", before: "—(••÷[", after: "]÷••)—"),
      Transformer(name: "Decoration ", before: "•]••´º´•»", after: "«•´º´••[•"),
      Transformer(name: "Decoration ", before: "*•.¸♡", after: "♡¸.•*"),
      Transformer(name: "Decoration ", before: "╰☆☆", after: "☆☆╮"),
      Transformer(name: "Decoration ", before: "↤↤↤↤↤↤", after: "↦↦↦↦↦↦"),
      Transformer(name: "Decoration ", before: "➶➶➶➶➶➶", after: "➷➷➷➷➷➷"),
      Transformer(name: "Decoration ", before: "↫↫↫↫↫", after: "↬↬↬↬↬"),
      Transformer(name: "Decoration ", before: "╚»★«╝", after: "╚»★«╝"),
      Transformer(name: "Decoration ", before: "•´¯`•.", after: ".•´¯`•"),
      Transformer(name: "Decoration ", before: "§.•´¨'°÷•..×", after: "×,.•´¨'°÷•..§"),
      Transformer(name: "Decoration ", before: "•°¯`••", after: "••´¯°•"),
      Transformer(name: "Decoration ", before: "]|I{•------»", after: "«------•}I|["),
      Transformer(name: "Decoration ", before: "(-_-)", after: "(-_-)"),
      Transformer(name: "Decoration ", before: "•´¯`•.", after: ".•´¯`•"),
      Transformer(name: "Decoration ", before: "-漫~*'¨¯¨'*·舞~", after: "~舞*'¨¯¨'*·~漫-"),
      Transformer(name: "Decoration ", before: "¤¸¸.•´¯`•¸¸.•..>>", after: "<<..•.¸¸•´¯`•.¸¸¤"),
      Transformer(name: "Decoration ", before: "๑۞๑,¸¸,ø¤º°`°๑۩", after: "๑۩ ,¸¸,ø¤º°`°๑۞๑"),
      Transformer(name: "Decoration ", before: ".•°¤*(¯`★´¯)*¤°", after: "°¤*(¯´★`¯)*¤°•."),
      Transformer(name: "Decoration ", before: "••.•´¯`•.••", after: "••.•´¯`•.••"),
      Transformer(name: "Decoration ", before: ".o0×X×0o.", after: ".o0×X×0o."),
      Transformer(name: "Decoration ", before: "ıllıllı", after: "ıllıllı"),
      Transformer(name: "Decoration ", before: "▀▄▀▄▀▄", after: "▄▀▄▀▄▀"),
      Transformer(name: "Decoration ", before: "▁ ▂ ▄ ▅ ▆ ▇ █", after: "█ ▇ ▆ ▅ ▄ ▂ ▁"),
      Transformer(name: "Decoration ", before: "▌│█║▌║▌║", after: "║▌║▌║█│▌"),
      Transformer(name: "Decoration ", before: "░▒▓█", after: "█▓▒░"),
      Transformer(name: "Decoration ", before: "░▒▓█►─═", after: "═─◄█▓▒░"),
      Transformer(name: "Decoration ", before: "ஜ۩۞۩ஜ", after: "ஜ۩۞۩ஜ"),
      Transformer(name: "Decoration ", before: "★彡", after: "彡★"),
      Transformer(name: "Decoration ", before: "◦•●◉✿", after: "✿◉●•◦"),
      Transformer(name: "Decoration ", before: "۰۪۫ ۪۫☃۰۪۫ ۪۫ ", after: "۰۪۫ ۪۫☃۰۪۫ ۪۫ "),
      Transformer(name: "Decoration ", before: "✦ (　-_･) ︻デ═一 ▸", after: "(/❛o❛)/ ✦"),
      Transformer(name: "Decoration ", before: "♔ (◐ ε ◑)", after: "(◐ ε ◑) ♔"),
      Transformer(name: "Decoration ", before: "★ 乂❤‿❤乂", after: "乂❤‿❤乂 ★"),
      Transformer(name: "Decoration ", before: "¯\\_(ツ)_/¯", after: "¯\\_(ツ)_/¯"),
      Transformer(name: "Decoration ", before: "♬♪♫", after: "ヾ(*・。・)ﾉ ♬♪♫"),
      Transformer(name: "Decoration ", before: "꧁꧂ ヽ(⌐■_■)ノ♪♬", after: "♬♪♫ ꧁꧂"),
      Transformer(name: "Decoration ", before: "ƪ(˘⌣˘)┐", after: "┌(˘⌣˘)ʃ"),
      Transformer(name: "Decoration ", before: "( ˘ ³˘)❤", after: "( ˘ ³˘)❤"),
      Transformer(name: "Decoration ", before: "༼ つ ◕_◕ ༽つ", after: "༼ つ ◕_◕ ༽つ"),
      Transformer(name: "Decoration ", before: "ヘ( ^o^)ノ", after: "＼(^_^ )"),
      Transformer(name: "Decoration ", before: "(~˘▾˘)~", after: "~(˘▾˘~)"),
      Transformer(name: "Decoration ", before: "└(^o^ )", after: "( ^o^)┘")
    ]
  }

}
