import Foundation

enum DecorationTransformers {

  static let all: [Transformer.Grouping] = [
    (groupName: "All Decorations", transformers: [
      Transformer(name: "Decoration 1", before: "`•.,¸¸,.•´¯", after: "¯`•.,¸¸,.•´"),
      Transformer(name: "Decoration 2", before: "¸,ø¤º°`°º¤ø,¸", after: "¸,ø¤º°`°º¤ø,¸"),
      Transformer(name: "Decoration 3", before: "★·.·´¯`·.·★", after: "★·.·´¯`·.·★"),
      Transformer(name: "Decoration 4", before: "¸„.-•~¹°”ˆ˜¨", after: "¨˜ˆ”°¹~•-.„¸"),
      Transformer(name: "Decoration 5", before: "·.¸¸.·♩♪♫", after: "♫♪♩·.¸¸.·"),
      Transformer(name: "Decoration 6", before: "×º°”˜`”°º×", after: "×º°”˜`”°º×"),
      Transformer(name: "Decoration 7", before: "•?((¯°·._.•", after: "•._.·°¯))؟•"),
      Transformer(name: "Decoration 8", before: "(¯´•._.•", after: "•._.•´¯)"),
      Transformer(name: "Decoration 9", before: "¸„.-•~¹°”ˆ˜¨", after: "¨˜ˆ”°¹~•-.„¸"),
      Transformer(name: "Decoration 10", before: "|!¤*'~``~'*¤!|", after: "|!¤*'~``~'*¤!|"),
      Transformer(name: "Decoration 11", before: "(¯`·.¸¸.·´¯`·.¸¸.->", after: "<-.¸¸.·´¯`·.¸¸.·´¯)"),
      Transformer(name: "Decoration 12", before: ",-*' ^ '~*-.,_,.-*~", after: "~*-.,_,.-*~' ^ '*-,"),
      Transformer(name: "Decoration 13", before: "°°°·.°·..·°¯°·._.·", after: "·._.·°¯°·.·° .·°°°"),
      Transformer(name: "Decoration 14", before: "•._.••´¯``•.¸¸.•`", after: "`•.¸¸.•´´¯`••._.•"),
      Transformer(name: "Decoration 15", before: "¸,ø¤º°`°º¤ø,¸¸,ø¤º°", after: "°º¤ø,¸¸,ø¤º°`°º¤ø,¸"),
      Transformer(name: "Decoration 16", before: ".•°¤*(¯`★´¯)*¤°", after: "°¤*(¯´★`¯)*¤°•."),
      Transformer(name: "Decoration 17", before: "¤¸¸.•´¯`•¸¸.•..>>", after: "<<..•.¸¸•´¯`•.¸¸¤"),
      Transformer(name: "Decoration 18", before: "`•.¸¸.•´´¯`••._.•", after: "•._.••`¯´´•.¸¸.•`"),
      Transformer(name: "Decoration 19", before: "(¯´•._.•", after: "•._.•´¯)"),
      Transformer(name: "Decoration 20", before: "••¤(`×[¤", after: "¤]×´)¤••"),
      Transformer(name: "Decoration 21", before: "•´¯`•»", after: "«•´¯`•"),
      Transformer(name: "Decoration 22", before: "—(••÷[", after: "]÷••)—"),
      Transformer(name: "Decoration 23", before: "•]••´º´•»", after: "«•´º´••[•"),
      Transformer(name: "Decoration 24", before: "*•.¸♡", after: "♡¸.•*"),
      Transformer(name: "Decoration 25", before: "╰☆☆", after: "☆☆╮"),
      Transformer(name: "Decoration 26", before: "↤↤↤↤↤↤", after: "↦↦↦↦↦↦"),
      Transformer(name: "Decoration 27", before: "➶➶➶➶➶➶", after: "➷➷➷➷➷➷"),
      Transformer(name: "Decoration 28", before: "↫↫↫↫↫", after: "↬↬↬↬↬"),
      Transformer(name: "Decoration 29", before: "╚»★«╝", after: "╚»★«╝"),
      Transformer(name: "Decoration 30", before: "•´¯`•.", after: ".•´¯`•"),
      Transformer(name: "Decoration 31", before: "§.•´¨'°÷•..×", after: "×,.•´¨'°÷•..§"),
      Transformer(name: "Decoration 32", before: "•°¯`••", after: "••´¯°•"),
      Transformer(name: "Decoration 33", before: "]|I{•------»", after: "«------•}I|["),
      Transformer(name: "Decoration 34", before: "(-_-)", after: "(-_-)"),
      Transformer(name: "Decoration 35", before: "•´¯`•.", after: ".•´¯`•"),
      Transformer(name: "Decoration 36", before: "-漫~*'¨¯¨'*·舞~", after: "~舞*'¨¯¨'*·~漫-"),
      Transformer(name: "Decoration 37", before: "¤¸¸.•´¯`•¸¸.•..>>", after: "<<..•.¸¸•´¯`•.¸¸¤"),
      Transformer(name: "Decoration 38", before: "๑۞๑,¸¸,ø¤º°`°๑۩", after: "๑۩ ,¸¸,ø¤º°`°๑۞๑"),
      Transformer(name: "Decoration 39", before: ".•°¤*(¯`★´¯)*¤°", after: "°¤*(¯´★`¯)*¤°•."),
      Transformer(name: "Decoration 40", before: "••.•´¯`•.••", after: "••.•´¯`•.••"),
      Transformer(name: "Decoration 41", before: ".o0×X×0o.", after: ".o0×X×0o."),
      Transformer(name: "Decoration 42", before: "ıllıllı", after: "ıllıllı"),
      Transformer(name: "Decoration 43", before: "▀▄▀▄▀▄", after: "▄▀▄▀▄▀"),
      Transformer(name: "Decoration 44", before: "▁ ▂ ▄ ▅ ▆ ▇ █", after: "█ ▇ ▆ ▅ ▄ ▂ ▁"),
      Transformer(name: "Decoration 45", before: "▌│█║▌║▌║", after: "║▌║▌║█│▌"),
      Transformer(name: "Decoration 46", before: "░▒▓█", after: "█▓▒░"),
      Transformer(name: "Decoration 47", before: "░▒▓█►─═", after: "═─◄█▓▒░"),
      Transformer(name: "Decoration 48", before: "ஜ۩۞۩ஜ", after: "ஜ۩۞۩ஜ"),
      Transformer(name: "Decoration 49", before: "★彡", after: "彡★"),
      Transformer(name: "Decoration 50", before: "◦•●◉✿", after: "✿◉●•◦"),
      Transformer(name: "Decoration 51", before: "۰۪۫ ۪۫☃۰۪۫ ۪۫ ", after: "۰۪۫ ۪۫☃۰۪۫ ۪۫ "),
      Transformer(name: "Decoration 52", before: "✦ (　-_･) ︻デ═一 ▸", after: "(/❛o❛)/ ✦"),
      Transformer(name: "Decoration 53", before: "♔ (◐ ε ◑)", after: "(◐ ε ◑) ♔"),
      Transformer(name: "Decoration 54", before: "★ 乂❤‿❤乂", after: "乂❤‿❤乂 ★"),
      Transformer(name: "Decoration 55", before: "¯\\_(ツ)_/¯", after: "¯\\_(ツ)_/¯"),
      Transformer(name: "Decoration 56", before: "♬♪♫", after: "ヾ(*・。・)ﾉ ♬♪♫"),
      Transformer(name: "Decoration 57", before: "꧁꧂ ヽ(⌐■_■)ノ♪♬", after: "♬♪♫ ꧁꧂"),
      Transformer(name: "Decoration 58", before: "ƪ(˘⌣˘)┐", after: "┌(˘⌣˘)ʃ"),
      Transformer(name: "Decoration 59", before: "( ˘ ³˘)❤", after: "( ˘ ³˘)❤"),
      Transformer(name: "Decoration 60", before: "༼ つ ◕_◕ ༽つ", after: "༼ つ ◕_◕ ༽つ"),
      Transformer(name: "Decoration 61", before: "ヘ( ^o^)ノ", after: "＼(^_^ )"),
      Transformer(name: "Decoration 62", before: "(~˘▾˘)~", after: "~(˘▾˘~)"),
      Transformer(name: "Decoration 63", before: "└(^o^ )", after: "( ^o^)┘")
    ])
  ]

}
